### ISSUE TITLE
Draft the Screens

### ISSUE THREAD

**Issue by anacchp** [Alissonfelipe1234/utopyan#2]

**Comment by Alissonfelipe1234** [comment]
![search screen](https://raw.githubusercontent.com/Alissonfelipe1234/utopyan/develop/.preview/search_screen.png)
![login screen](https://raw.githubusercontent.com/Alissonfelipe1234/utopyan/develop/.preview/login_screen.png)
![main screen](https://raw.githubusercontent.com/Alissonfelipe1234/utopyan/develop/.preview/main_screen.png)
![list screen](https://raw.githubusercontent.com/Alissonfelipe1234/utopyan/develop/.preview/my_list.png)
